name: Cloud SQL Proxy
description: Run the Google Cloud SQL Proxy in a GitHub Action's context

branding:
  icon: database
  color: blue

inputs:
  key:
    description: Service Account JSON Key
    required: false

  connection:
    description: CloudSQL instance connection name, e.g. project:region:instance
    required: true

  port:
    description: Listening port
    required: true

runs:
  using: composite
  steps:
    - name: "sql-proxy: start container"
      run: ${{ github.action_path }}/scripts/proxy.sh ${{ inputs.connection }}
      shell: bash

    - name: "sql-proxy: wait for connection"
      run: ${{ github.action_path }}/scripts/wait.sh ${{ inputs.port }} 3 10
      shell: bash
